### ISSUE TITLE
Allow removal of added points

### ISSUE THREAD

**Issue by Pebaz** [ulido/quadtree#1]
Could you add a `remove(pos, id_)` method that would allow me to remove a specified point/id combo?

**Comment by ulido** [comment]
It would be possible to implement. However, it's inefficient if you remove many entries (in that case it is likely much more efficient to simply rebuild the tree). And if you only remove a few entries it's better to keep an external list of removed ids to check against. Quadtrees are not designed for removing entries. What is your usecase for this?

**Comment by Pebaz** [comment]
Hello, thanks for the reply!

Actually, what you recommended will actually solve my problem! I'll keep a
list of removed IDs to check against.

Thanks!

**Comment by ulido** [comment]
That's great! Happy to help.
